n1= input('Digite algo ')
print('O tipo primitivo é',type(n1))
print('É um numero? {}'.format(n1.isnumeric()))
print('É alfabético? {}'.format(n1.isalpha()))
print('Tem somente número ou letra (Alfanumérico)? {}'.format(n1.isalnum()))
print('Todas as letras são maiúsculas? {}'.format(n1.isupper()))
print('Todas as letras são minusculas? {}'.format(n1.islower()))
print('Tem somente espaço? {}'.format(n1.isspace()))
print('Esta capitalizada? (Maiusculas primeiro) {}'.format(n1.istitle()))